### ISSUE TITLE
Не компилится под sm 1.10

### ISSUE THREAD

**Issue by kleuser75** [ExtendedPlugs/NicknameProtect#2]
Так как 1.10 вышел в стабильную ветку, требуется обновить плагин. Сейчас он не компилится

//// NicknameProtect.sp
//
// D:\Dev\sm110\scripting\NicknameProtect.sp(42) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// D:\Dev\sm110\scripting\NicknameProtect.sp(102) : error 001: expected token: "(", but found "-identifier-"
// D:\Dev\sm110\scripting\NicknameProtect.sp(102) : error 130: cannot coerce functions to values
// D:\Dev\sm110\scripting\NicknameProtect.sp(105) : error 001: expected token: "(", but found "!"
// D:\Dev\sm110\scripting\NicknameProtect.sp(105) : error 130: cannot coerce functions to values
// D:\Dev\sm110\scripting\NicknameProtect.sp(148) : error 001: expected token: "(", but found "!"
// D:\Dev\sm110\scripting\NicknameProtect.sp(148) : error 130: cannot coerce functions to values
// D:\Dev\sm110\scripting\NicknameProtect.sp(150) : error 001: expected token: "(", but found "-identifier-"
// D:\Dev\sm110\scripting\NicknameProtect.sp(151) : error 017: undefined symbol "then"
//
// 8 Errors.
//
// Compilation Time: 0,23 sec
// ----------------------------------------

**Comment by whyAries** [comment]
@kleuser75 залил билд, проверить пока нет возможности
